# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kanu
spring.datasource.username=kcuser
spring.datasource.password=kcpassword

# ===============================
# Keycloak
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9080/realms/KanuControl

# ===============================
# Liquibase
# ===============================
spring.liquibase.enabled=false
spring.liquibase.default-schema=kanu

# ===============================
# Multi Tenancy
# ===============================
spring.jpa.properties.hibernate.multi_tenancy=SCHEMA

# ===============================
# CORS
# ===============================
kcserver.cors.allowed-origin-patterns=http://localhost:5173,http://192.168.100.*:5173