# ===============================
# Datasource
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Keycloak
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.kanucontrol.de/realms/KanuControl

# ===============================
# Liquibase
# ===============================
spring.liquibase.enabled=false
spring.liquibase.default-schema=kanu

# ===============================
# Multi Tenancy
# ===============================
spring.jpa.properties.hibernate.multi_tenancy=SCHEMA

# ===============================
# CORS
# ===============================
kcserver.cors.allowed-origin-patterns=https://kc.kanucontrol.de