# ===============================
# App Version
# ===============================
app.version=0.9.5
app.environment=PROD
# ===============================
# Server
# ===============================
server.port=8090
spring.application.name=kc_server
spring.main.banner-mode=off

# ===============================
# Pageable
# ===============================
spring.data.web.pageable.default-page-size=500
spring.data.web.pageable.max-page-size=1000

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# ===============================
# Logging
# ===============================
# logging.level.org.springframework.boot.context.config=INFO
logging.level.com.kcserver.tenancy=ERROR
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.com.kcserver=ERROR

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always