# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://192.168.100.31:5432/kanucontrol
spring.datasource.username=kcuser
spring.datasource.password=CHsab581&KanuControl2026!

# ===============================
# Keycloak
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.100.33:8080/realms/KanuControl

# ===============================
# Liquibase
# ===============================
spring.liquibase.enabled=false
spring.liquibase.default-schema=kanu

# ===============================
# Multi Tenancy
# ===============================
spring.jpa.properties.hibernate.multi_tenancy=SCHEMA

# ===============================
# CORS
# ===============================
kcserver.cors.allowed-origin-patterns=http://192.168.100.34
# kcserver.cors.allowed-origin-patterns=https://kanucontrol.de