--
-- PostgreSQL database dump
--

\restrict Nh85dI1tqR6b6qwwOumXdTApbrL1TmAPJQ0NvD7Nxqz6QCWjorXaAGDpj9bH0Ce

-- Dumped from database version 16.11 (Homebrew)
-- Dumped by pg_dump version 16.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ekc_test; Type: SCHEMA; Schema: -; Owner: kcuser
--

CREATE SCHEMA ekc_test;


ALTER SCHEMA ekc_test OWNER TO kcuser;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: abrechnung; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.abrechnung (
    id bigint NOT NULL,
    veranstaltung_id bigint NOT NULL,
    status character varying(30) DEFAULT 'OFFEN'::character varying NOT NULL,
    verwendeter_foerdersatz numeric(10,2)
);


ALTER TABLE ekc_test.abrechnung OWNER TO kcuser;

--
-- Name: abrechnung_beleg; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.abrechnung_beleg (
    id bigint NOT NULL,
    abrechnung_id bigint NOT NULL,
    beleg_nummer character varying(50) NOT NULL,
    rechnungsnummer character varying(100),
    datum date NOT NULL,
    beschreibung character varying(500),
    finanz_gruppe_id bigint NOT NULL,
    lfd_nr integer NOT NULL
);


ALTER TABLE ekc_test.abrechnung_beleg OWNER TO kcuser;

--
-- Name: abrechnung_beleg_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.abrechnung_beleg ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.abrechnung_beleg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: abrechnung_buchung; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.abrechnung_buchung (
    id bigint NOT NULL,
    kategorie character varying(40) NOT NULL,
    betrag numeric(12,2) NOT NULL,
    datum date NOT NULL,
    beschreibung character varying(500),
    beleg_id bigint NOT NULL
);


ALTER TABLE ekc_test.abrechnung_buchung OWNER TO kcuser;

--
-- Name: abrechnung_buchung_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.abrechnung_buchung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.abrechnung_buchung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: abrechnung_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.abrechnung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.abrechnung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: erhebungsbogen; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.erhebungsbogen (
    id bigint NOT NULL,
    veranstaltung_id bigint NOT NULL,
    abgeschlossen boolean NOT NULL,
    stichtag date NOT NULL,
    teilnehmer_maennlich_u6 integer,
    teilnehmer_maennlich_6_13 integer,
    teilnehmer_maennlich_14_17 integer,
    teilnehmer_maennlich_18_plus integer,
    teilnehmer_weiblich_u6 integer,
    teilnehmer_weiblich_6_13 integer,
    teilnehmer_weiblich_14_17 integer,
    teilnehmer_weiblich_18_plus integer,
    teilnehmer_divers_u6 integer,
    teilnehmer_divers_6_13 integer,
    teilnehmer_divers_14_17 integer,
    teilnehmer_divers_18_plus integer,
    mitarbeiter_maennlich integer,
    mitarbeiter_weiblich integer,
    mitarbeiter_divers integer,
    bemerkung character varying(500),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(100),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(100)
);


ALTER TABLE ekc_test.erhebungsbogen OWNER TO kcuser;

--
-- Name: erhebungsbogen_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.erhebungsbogen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.erhebungsbogen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanz_gruppe; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.finanz_gruppe (
    id bigint NOT NULL,
    kuerzel character varying(20) NOT NULL,
    veranstaltung_id bigint NOT NULL
);


ALTER TABLE ekc_test.finanz_gruppe OWNER TO kcuser;

--
-- Name: finanz_gruppe_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.finanz_gruppe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.finanz_gruppe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: foerdersatz; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.foerdersatz (
    id bigint NOT NULL,
    gueltig_von date NOT NULL,
    gueltig_bis date,
    foerdersatz numeric(10,2) NOT NULL,
    beschluss character varying(255),
    typ character varying(20) NOT NULL
);


ALTER TABLE ekc_test.foerdersatz OWNER TO kcuser;

--
-- Name: foerdersatz_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.foerdersatz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.foerdersatz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kik_zuschlag; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.kik_zuschlag (
    id bigint NOT NULL,
    gueltig_von date NOT NULL,
    gueltig_bis date,
    kik_zuschlag numeric(10,2) NOT NULL,
    beschluss character varying(255)
);


ALTER TABLE ekc_test.kik_zuschlag OWNER TO kcuser;

--
-- Name: kik_zuschlag_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.kik_zuschlag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.kik_zuschlag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mitglied; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.mitglied (
    id bigint NOT NULL,
    person_id bigint NOT NULL,
    verein_id bigint NOT NULL,
    funktion character varying(50),
    haupt_verein boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(100),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(100)
);


ALTER TABLE ekc_test.mitglied OWNER TO kcuser;

--
-- Name: mitglied_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.mitglied ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.mitglied_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.person (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    vorname character varying(100) NOT NULL,
    geburtsdatum date,
    sex character(1) NOT NULL,
    email character varying(255),
    aktiv boolean DEFAULT true NOT NULL,
    strasse character varying(255),
    plz character varying(20),
    ort character varying(100),
    country_code character(2),
    telefon character varying(50),
    telefon_festnetz character varying(50),
    bank_name character varying(255),
    iban character varying(34),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(255),
    bic character varying(20),
    efz date,
    CONSTRAINT ck_person_sex CHECK ((sex = ANY (ARRAY['M'::bpchar, 'W'::bpchar, 'D'::bpchar])))
);


ALTER TABLE ekc_test.person OWNER TO kcuser;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planung; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.planung (
    id bigint NOT NULL,
    veranstaltung_id bigint NOT NULL,
    eingereicht boolean DEFAULT false NOT NULL
);


ALTER TABLE ekc_test.planung OWNER TO kcuser;

--
-- Name: planung_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.planung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.planung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planung_position; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.planung_position (
    id bigint NOT NULL,
    planung_id bigint NOT NULL,
    kategorie character varying(40) NOT NULL,
    betrag numeric(12,2) NOT NULL,
    kommentar character varying(500)
);


ALTER TABLE ekc_test.planung_position OWNER TO kcuser;

--
-- Name: planung_position_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.planung_position ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.planung_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teilnehmer; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.teilnehmer (
    id bigint NOT NULL,
    veranstaltung_id bigint NOT NULL,
    person_id bigint NOT NULL,
    rolle character(1),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(255),
    individueller_beitrag numeric(10,2),
    finanz_gruppe_id bigint,
    bezahlt boolean DEFAULT false,
    bezahlt_am date
);


ALTER TABLE ekc_test.teilnehmer OWNER TO kcuser;

--
-- Name: teilnehmer_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.teilnehmer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.teilnehmer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: veranstaltung; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.veranstaltung (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    typ character(3) NOT NULL,
    art_der_unterkunft character varying(200),
    art_der_verpflegung character varying(200),
    plz character varying(20),
    ort character varying(200),
    country_code character(2),
    beginn_datum date NOT NULL,
    beginn_zeit time without time zone NOT NULL,
    ende_datum date NOT NULL,
    ende_zeit time without time zone NOT NULL,
    verein_id bigint NOT NULL,
    leiter_id bigint NOT NULL,
    geplante_teilnehmer_maennlich integer,
    geplante_teilnehmer_weiblich integer,
    geplante_teilnehmer_divers integer,
    geplante_mitarbeiter_maennlich integer,
    geplante_mitarbeiter_weiblich integer,
    geplante_mitarbeiter_divers integer,
    aktiv boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(255),
    individuelle_gebuehren boolean DEFAULT false NOT NULL,
    standard_gebuehr numeric(10,2),
    scope character varying(20)
);


ALTER TABLE ekc_test.veranstaltung OWNER TO kcuser;

--
-- Name: COLUMN veranstaltung.individuelle_gebuehren; Type: COMMENT; Schema: ekc_test; Owner: kcuser
--

COMMENT ON COLUMN ekc_test.veranstaltung.individuelle_gebuehren IS 'false = eine Gebühr für alle';


--
-- Name: COLUMN veranstaltung.standard_gebuehr; Type: COMMENT; Schema: ekc_test; Owner: kcuser
--

COMMENT ON COLUMN ekc_test.veranstaltung.standard_gebuehr IS 'Standard Teilnehmergebühr';


--
-- Name: veranstaltung_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.veranstaltung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.veranstaltung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verein; Type: TABLE; Schema: ekc_test; Owner: kcuser
--

CREATE TABLE ekc_test.verein (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    abk character varying(10) NOT NULL,
    strasse character varying(255),
    plz character varying(20),
    ort character varying(100),
    telefon character varying(50),
    bank_name character varying(255),
    iban character varying(34),
    kontoinhaber_id bigint,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(100),
    last_modified_at timestamp without time zone,
    last_modified_by character varying(100),
    bic character varying(20),
    schutzkonzept date,
    kik_zertifiziert_seit date,
    kik_zertifiziert_bis date
);


ALTER TABLE ekc_test.verein OWNER TO kcuser;

--
-- Name: verein_id_seq; Type: SEQUENCE; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ekc_test.verein ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ekc_test.verein_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: abrechnung; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.abrechnung (id, veranstaltung_id, status, verwendeter_foerdersatz) FROM stdin;
\.


--
-- Data for Name: abrechnung_beleg; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.abrechnung_beleg (id, abrechnung_id, beleg_nummer, rechnungsnummer, datum, beschreibung, finanz_gruppe_id, lfd_nr) FROM stdin;
\.


--
-- Data for Name: abrechnung_buchung; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.abrechnung_buchung (id, kategorie, betrag, datum, beschreibung, beleg_id) FROM stdin;
\.


--
-- Data for Name: erhebungsbogen; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.erhebungsbogen (id, veranstaltung_id, abgeschlossen, stichtag, teilnehmer_maennlich_u6, teilnehmer_maennlich_6_13, teilnehmer_maennlich_14_17, teilnehmer_maennlich_18_plus, teilnehmer_weiblich_u6, teilnehmer_weiblich_6_13, teilnehmer_weiblich_14_17, teilnehmer_weiblich_18_plus, teilnehmer_divers_u6, teilnehmer_divers_6_13, teilnehmer_divers_14_17, teilnehmer_divers_18_plus, mitarbeiter_maennlich, mitarbeiter_weiblich, mitarbeiter_divers, bemerkung, created_at, created_by, last_modified_at, last_modified_by) FROM stdin;
\.


--
-- Data for Name: finanz_gruppe; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.finanz_gruppe (id, kuerzel, veranstaltung_id) FROM stdin;
\.


--
-- Data for Name: foerdersatz; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.foerdersatz (id, gueltig_von, gueltig_bis, foerdersatz, beschluss, typ) FROM stdin;
\.


--
-- Data for Name: kik_zuschlag; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.kik_zuschlag (id, gueltig_von, gueltig_bis, kik_zuschlag, beschluss) FROM stdin;
\.


--
-- Data for Name: mitglied; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.mitglied (id, person_id, verein_id, funktion, haupt_verein, created_at, created_by, last_modified_at, last_modified_by) FROM stdin;
\.


--
-- Data for Name: person; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.person (id, name, vorname, geburtsdatum, sex, email, aktiv, strasse, plz, ort, country_code, telefon, telefon_festnetz, bank_name, iban, created_at, created_by, last_modified_at, last_modified_by, bic, efz) FROM stdin;
\.


--
-- Data for Name: planung; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.planung (id, veranstaltung_id, eingereicht) FROM stdin;
\.


--
-- Data for Name: planung_position; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.planung_position (id, planung_id, kategorie, betrag, kommentar) FROM stdin;
\.


--
-- Data for Name: teilnehmer; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.teilnehmer (id, veranstaltung_id, person_id, rolle, created_at, created_by, last_modified_at, last_modified_by, individueller_beitrag, finanz_gruppe_id, bezahlt, bezahlt_am) FROM stdin;
\.


--
-- Data for Name: veranstaltung; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.veranstaltung (id, name, typ, art_der_unterkunft, art_der_verpflegung, plz, ort, country_code, beginn_datum, beginn_zeit, ende_datum, ende_zeit, verein_id, leiter_id, geplante_teilnehmer_maennlich, geplante_teilnehmer_weiblich, geplante_teilnehmer_divers, geplante_mitarbeiter_maennlich, geplante_mitarbeiter_weiblich, geplante_mitarbeiter_divers, aktiv, created_at, created_by, last_modified_at, last_modified_by, individuelle_gebuehren, standard_gebuehr, scope) FROM stdin;
\.


--
-- Data for Name: verein; Type: TABLE DATA; Schema: ekc_test; Owner: kcuser
--

COPY ekc_test.verein (id, name, abk, strasse, plz, ort, telefon, bank_name, iban, kontoinhaber_id, created_at, created_by, last_modified_at, last_modified_by, bic, schutzkonzept, kik_zertifiziert_seit, kik_zertifiziert_bis) FROM stdin;
\.


--
-- Name: abrechnung_beleg_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.abrechnung_beleg_id_seq', 1, false);


--
-- Name: abrechnung_buchung_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.abrechnung_buchung_id_seq', 1, false);


--
-- Name: abrechnung_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.abrechnung_id_seq', 1, false);


--
-- Name: erhebungsbogen_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.erhebungsbogen_id_seq', 1, false);


--
-- Name: finanz_gruppe_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.finanz_gruppe_id_seq', 1, false);


--
-- Name: foerdersatz_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.foerdersatz_id_seq', 1, false);


--
-- Name: kik_zuschlag_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.kik_zuschlag_id_seq', 1, false);


--
-- Name: mitglied_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.mitglied_id_seq', 1, false);


--
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.person_id_seq', 1, false);


--
-- Name: planung_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.planung_id_seq', 1, false);


--
-- Name: planung_position_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.planung_position_id_seq', 1, false);


--
-- Name: teilnehmer_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.teilnehmer_id_seq', 1, false);


--
-- Name: veranstaltung_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.veranstaltung_id_seq', 1, false);


--
-- Name: verein_id_seq; Type: SEQUENCE SET; Schema: ekc_test; Owner: kcuser
--

SELECT pg_catalog.setval('ekc_test.verein_id_seq', 1, false);


--
-- Name: abrechnung_beleg abrechnung_beleg_abrechnung_id_beleg_nummer_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.abrechnung_beleg
    ADD CONSTRAINT abrechnung_beleg_abrechnung_id_beleg_nummer_key UNIQUE (abrechnung_id, beleg_nummer);


--
-- Name: abrechnung_beleg abrechnung_beleg_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.abrechnung_beleg
    ADD CONSTRAINT abrechnung_beleg_pkey PRIMARY KEY (id);


--
-- Name: abrechnung_buchung abrechnung_buchung_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.abrechnung_buchung
    ADD CONSTRAINT abrechnung_buchung_pkey PRIMARY KEY (id);


--
-- Name: abrechnung abrechnung_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.abrechnung
    ADD CONSTRAINT abrechnung_pkey PRIMARY KEY (id);


--
-- Name: abrechnung abrechnung_veranstaltung_id_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.abrechnung
    ADD CONSTRAINT abrechnung_veranstaltung_id_key UNIQUE (veranstaltung_id);


--
-- Name: erhebungsbogen erhebungsbogen_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.erhebungsbogen
    ADD CONSTRAINT erhebungsbogen_pkey PRIMARY KEY (id);


--
-- Name: erhebungsbogen erhebungsbogen_veranstaltung_id_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.erhebungsbogen
    ADD CONSTRAINT erhebungsbogen_veranstaltung_id_key UNIQUE (veranstaltung_id);


--
-- Name: finanz_gruppe finanz_gruppe_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.finanz_gruppe
    ADD CONSTRAINT finanz_gruppe_pkey PRIMARY KEY (id);


--
-- Name: finanz_gruppe finanz_gruppe_veranstaltung_id_kuerzel_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.finanz_gruppe
    ADD CONSTRAINT finanz_gruppe_veranstaltung_id_kuerzel_key UNIQUE (veranstaltung_id, kuerzel);


--
-- Name: foerdersatz foerdersatz_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.foerdersatz
    ADD CONSTRAINT foerdersatz_pkey PRIMARY KEY (id);


--
-- Name: foerdersatz foerdersatz_typ_daterange_excl; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.foerdersatz
    ADD CONSTRAINT foerdersatz_typ_daterange_excl EXCLUDE USING gist (typ WITH =, daterange(gueltig_von, gueltig_bis, '[]'::text) WITH &&);


--
-- Name: foerdersatz foerdersatz_typ_gueltig_von_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.foerdersatz
    ADD CONSTRAINT foerdersatz_typ_gueltig_von_key UNIQUE (typ, gueltig_von);


--
-- Name: kik_zuschlag kik_zuschlag_daterange_excl; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.kik_zuschlag
    ADD CONSTRAINT kik_zuschlag_daterange_excl EXCLUDE USING gist (daterange(gueltig_von, gueltig_bis, '[]'::text) WITH &&);


--
-- Name: kik_zuschlag kik_zuschlag_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.kik_zuschlag
    ADD CONSTRAINT kik_zuschlag_pkey PRIMARY KEY (id);


--
-- Name: mitglied mitglied_person_id_verein_id_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.mitglied
    ADD CONSTRAINT mitglied_person_id_verein_id_key UNIQUE (person_id, verein_id);


--
-- Name: mitglied mitglied_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.mitglied
    ADD CONSTRAINT mitglied_pkey PRIMARY KEY (id);


--
-- Name: person person_name_vorname_geburtsdatum_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.person
    ADD CONSTRAINT person_name_vorname_geburtsdatum_key UNIQUE (name, vorname, geburtsdatum);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: planung planung_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.planung
    ADD CONSTRAINT planung_pkey PRIMARY KEY (id);


--
-- Name: planung_position planung_position_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.planung_position
    ADD CONSTRAINT planung_position_pkey PRIMARY KEY (id);


--
-- Name: planung_position planung_position_planung_id_kategorie_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.planung_position
    ADD CONSTRAINT planung_position_planung_id_kategorie_key UNIQUE (planung_id, kategorie);


--
-- Name: planung planung_veranstaltung_id_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.planung
    ADD CONSTRAINT planung_veranstaltung_id_key UNIQUE (veranstaltung_id);


--
-- Name: teilnehmer teilnehmer_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.teilnehmer
    ADD CONSTRAINT teilnehmer_pkey PRIMARY KEY (id);


--
-- Name: teilnehmer teilnehmer_veranstaltung_id_person_id_key; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.teilnehmer
    ADD CONSTRAINT teilnehmer_veranstaltung_id_person_id_key UNIQUE (veranstaltung_id, person_id);


--
-- Name: veranstaltung veranstaltung_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.veranstaltung
    ADD CONSTRAINT veranstaltung_pkey PRIMARY KEY (id);


--
-- Name: verein verein_pkey; Type: CONSTRAINT; Schema: ekc_test; Owner: kcuser
--

ALTER TABLE ONLY ekc_test.verein
    ADD CONSTRAINT verein_pkey PRIMARY KEY (id);


--
-- Name: abrechnung_beleg_finanz_gruppe_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX abrechnung_beleg_finanz_gruppe_id_idx ON ekc_test.abrechnung_beleg USING btree (finanz_gruppe_id);


--
-- Name: finanz_gruppe_veranstaltung_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX finanz_gruppe_veranstaltung_id_idx ON ekc_test.finanz_gruppe USING btree (veranstaltung_id);


--
-- Name: foerdersatz_gueltig_von_gueltig_bis_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX foerdersatz_gueltig_von_gueltig_bis_idx ON ekc_test.foerdersatz USING btree (gueltig_von, gueltig_bis);


--
-- Name: mitglied_haupt_verein_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX mitglied_haupt_verein_idx ON ekc_test.mitglied USING btree (haupt_verein);


--
-- Name: mitglied_person_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX mitglied_person_id_idx ON ekc_test.mitglied USING btree (person_id);


--
-- Name: mitglied_verein_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX mitglied_verein_id_idx ON ekc_test.mitglied USING btree (verein_id);


--
-- Name: person_aktiv_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX person_aktiv_idx ON ekc_test.person USING btree (aktiv);


--
-- Name: person_lower_lower1_geburtsdatum_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE UNIQUE INDEX person_lower_lower1_geburtsdatum_idx ON ekc_test.person USING btree (lower((name)::text), lower((vorname)::text), geburtsdatum) WHERE (geburtsdatum IS NOT NULL);


--
-- Name: teilnehmer_person_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX teilnehmer_person_id_idx ON ekc_test.teilnehmer USING btree (person_id);


--
-- Name: teilnehmer_veranstaltung_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX teilnehmer_veranstaltung_id_idx ON ekc_test.teilnehmer USING btree (veranstaltung_id);


--
-- Name: teilnehmer_veranstaltung_id_idx1; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE UNIQUE INDEX teilnehmer_veranstaltung_id_idx1 ON ekc_test.teilnehmer USING btree (veranstaltung_id) WHERE (rolle = 'L'::bpchar);


--
-- Name: veranstaltung_aktiv_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE UNIQUE INDEX veranstaltung_aktiv_idx ON ekc_test.veranstaltung USING btree (aktiv) WHERE (aktiv = true);


--
-- Name: veranstaltung_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX veranstaltung_id_idx ON ekc_test.veranstaltung USING btree (id) WHERE (aktiv = true);


--
-- Name: verein_kontoinhaber_id_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE INDEX verein_kontoinhaber_id_idx ON ekc_test.verein USING btree (kontoinhaber_id);


--
-- Name: verein_lower_lower1_idx; Type: INDEX; Schema: ekc_test; Owner: kcuser
--

CREATE UNIQUE INDEX verein_lower_lower1_idx ON ekc_test.verein USING btree (lower((abk)::text), lower((name)::text));


--
-- PostgreSQL database dump complete
--

\unrestrict Nh85dI1tqR6b6qwwOumXdTApbrL1TmAPJQ0NvD7Nxqz6QCWjorXaAGDpj9bH0Ce

