// src/api/enums/MitgliedFunktion.ts

export enum MitgliedFunktion {
  BOOTSHAUSWART = "BOOTSHAUSWART",
  JUGENDWART = "JUGENDWART",
  KASSENWART = "KASSENWART",
  VORSITZENDER = "VORSITZENDER",
  SPORTWART = "SPORTWART",
  JUGENDDELEGIERTER = "JUGENDDELEGIERTER",
  PSG_BEAUFTRAGTE = "PSG_BEAUFTRAGTE",
  WANDERWART = "WANDERWART",
  GESCHAEFTSFUEHRER = "GESCHAEFTSFUEHRER",
  // ggf. weitere aus dem Backend ergänzen
}
