export enum ReferenzObjekt {
  EIN_EURO_MUENZE = "EIN_EURO_MUENZE",
  ZWEI_EURO_MUENZE = "ZWEI_EURO_MUENZE",
  EINKAUFSCHIP = "EINKAUFSCHIP",
  EC_KARTE = "EC_KARTE",
  DIN_A4 = "DIN_A4",
  DIN_A5 = "DIN_A5",
}
