// src/api/enums/CountryCode.ts

export const COUNTRIES = [
  { code: "AD", label: "Andorra" },
  { code: "AL", label: "Albanien" },
  { code: "AT", label: "Österreich" },
  { code: "BA", label: "Bosnien und Herzegowina" },
  { code: "BE", label: "Belgien" },
  { code: "BG", label: "Bulgarien" },
  { code: "CH", label: "Schweiz" },
  { code: "CY", label: "Zypern" },
  { code: "CZ", label: "Tschechien" },
  { code: "DE", label: "Deutschland" },
  { code: "DK", label: "Dänemark" },
  { code: "EE", label: "Estland" },
  { code: "ES", label: "Spanien" },
  { code: "FI", label: "Finnland" },
  { code: "FR", label: "Frankreich" },
  { code: "GB", label: "Vereinigtes Königreich" },
  { code: "GR", label: "Griechenland" },
  { code: "HR", label: "Kroatien" },
  { code: "HU", label: "Ungarn" },
  { code: "IE", label: "Irland" },
  { code: "IS", label: "Island" },
  { code: "IT", label: "Italien" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Litauen" },
  { code: "LU", label: "Luxemburg" },
  { code: "LV", label: "Lettland" },
  { code: "MC", label: "Monaco" },
  { code: "ME", label: "Montenegro" },
  { code: "MK", label: "Nordmazedonien" },
  { code: "MT", label: "Malta" },
  { code: "NL", label: "Niederlande" },
  { code: "NO", label: "Norwegen" },
  { code: "PL", label: "Polen" },
  { code: "PT", label: "Portugal" },
  { code: "RO", label: "Rumänien" },
  { code: "RS", label: "Serbien" },
  { code: "SE", label: "Schweden" },
  { code: "SI", label: "Slowenien" },
  { code: "SK", label: "Slowakei" },
  { code: "SM", label: "San Marino" },
  { code: "TR", label: "Türkei" },
  { code: "UA", label: "Ukraine" },
  { code: "VA", label: "Vatikanstadt" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["code"];
