export enum PdfDokumentTyp {
  ANMELDUNG = "ANMELDUNG",
  ERHEBUNGSBOGEN = "ERHEBUNGSBOGEN",
  ABRECHNUNG = "ABRECHNUNG",
  TEILNEHMERLISTE = "TEILNEHMERLISTE",
  TEILNEHMER_DATENKONTROLLE = "TEILNEHMER_DATENKONTROLLE",
  REISEKOSTENABRECHNUNG = "REISEKOSTENABRECHNUNG",
  ZAHLUNGSNACHWEISE = "ZAHLUNGSNACHWEISE",
  BELEGE = "BELEGE",
}
